import json
from llm import llm
from langchain.tools import StructuredTool
from pydantic import BaseModel, Field


# Tool: Generate sql and python code for StreamLit Application


class CodeGenInput(BaseModel):
    prompt: str = Field(..., description="User Request")
    question: str = Field(..., description="Question generated by Question Generation tool.")
    db_schema: str = Field(..., description="The database schema including table and column definitions.")
    chart_type: str = Field(..., description="Chart type generated by question tool for visualization, e.g., bar, line")
    chart_header: str = Field(..., description="Title for the chart based on question")


def generate_code(prompt: str, question: str, chart_type: str, chart_header: str, db_schema: str):
    instruction = f""" 
    Using the following:
    User prompt: {prompt}
    Question: {question}
    PostgreSQL database schema: {db_schema}
    Chart header: {chart_header}
    Chart type: {chart_type}
    
    Generate:
    1. A valid and executable PostgreSQL query to answer each question:"{question}"
    2. Ensure query doesn't produce too many records. Such as use an aggregation query/functions 
    3. Write python function that in Try Except block:
        - Executes PostgreSQL query.
        - Saves records in a dataframe(df).
        - Creates "{chart_type}" for StreamLit Application along with header: {chart_header} using st.subheader()
        - Hide legend for {chart_type}. Example use showlegend=False to Hide legend.
        - Hides x-axis tick labels. Example use x-axis=dict(showticklabels=False).
        - Only when chart_type is 'Indicator', use fig.update_layout(height=90, margin=dict(l=0, r=0, t=0, b=0))
)
        Example:
        def function_name():
            sql_query="<query>"
            <python streamlit code only>
    4. Avoid error like Can only use .dt accessor with datetime like values.
    5. Avoid queries for round(double precision, integer) does not exist.
    6. Use ilike statements with % when using where clauses.
    7. Only use columns given in the schema. Do not invent new ones.
    
    Only output:
    - Python functions in JSON format with keys 'question', 'chart_type', 'function_name', 'streamlit_code'
    - For Database connection use db_connector = st.session_state['db_connector'] and
        use db_connector.execute_query(SQL_QUERY) to execute SQL Query. Don't create new database connection.
    - Import only necessary libraries like streamlit, sqlalchemy, pandas, plotly, matplotlib, seaborn
    - No explanation.
    """
    output = llm.invoke(instruction)
    response_proxy = output.content.strip("```json").strip("```")
    response = json.loads(response_proxy)
    return response


CodeGenTool = StructuredTool(
    name="code_generation_tool",
    func=generate_code,
    description="Useful in creating SQL queries using given database schema for question",
    args_schema=CodeGenInput
)
